const siteConfig = {
  gitHubRepo: "https://github.com/mattphelps/tporn-downloader",
  baseSiteName: "tPorn",
  baseSite: "https://tporn.xxx",
  siteName: "tPorn Downloader",
  siteURL: "https://tporndownloader.com",
  siteTitle: "tPorn Downloader – Download tPorn Videos for Free",
  siteDescription: "Want a FAST and FREE way to Download videos from tPorn? Download MP4 Videos in HD with one click!",
  faviconPath: "/images/favicons/tporn.ico",
  emailFormLink: "https://formspree.io/f/mjvqaqaz",
  adminEmail: "matt@leandme.com",
  downloaderList: "nsfw",
  colorTheme: "light",
  buttonColor: "#ff6ba5",
  apifyKey: "apify_api_3ladjpBkeHJSHYp2yPv9U594YEbQlD2iJYJ106",
  GATag: "G-E0NGVPCQHJ",
  functional: "no",
  promotedBrand: "iTubeGo",
  promotedBrandURL: "https://www.linkconnector.com/ta.php?lc=165043000012007099&url=https%3A%2F%2Fitubego.com%2Fpurchase%2Fbuy-itubego-mac",
  promotedBrandSlug: "itubego",
  headerButtonCTA: "Download HD - All Porn Sites",
  smartlink: "https://flirttalkonline.life/?u=qf5kaeb&o=wgkpxhg",
};

export default siteConfig;