const siteConfig = {
  gitHubRepo: "https://github.com/mattphelps/onlyfans-downloader",
  baseSiteName: "OnlyFans",
  baseSite: "https://onlyfans.com",
  siteName: "OnlyFans Video Downloader",
  siteURL: "https://onlydownloader.io",
  siteTitle: "OnlyFans Video Downloader – Download OnlyFans Videos for Free",
  siteDescription: "Want a FAST and FREE way to Download videos from OnlyFans? Download MP4 Videos in HD with one click!",
  faviconPath: "/images/favicons/onlyfans.ico",
  emailFormLink: "https://formspree.io/f/mjvqaqaz",
  adminEmail: "matt@leandme.com",
  downloaderList: "nsfw",
  colorTheme: "light",
  buttonColor: "#02aff0",
  apifyKey: "apify_api_3ladjpBkeHJSHYp2yPv9U594YEbQlD2iJYJ62",
  GATag: "G-1Q33J5ZDLF",
  functional: "no",
  promotedBrand: "iTubeGo",
  promotedBrandURL: "https://www.linkconnector.com/ta.php?lc=165043000012007099&url=https%3A%2F%2Fitubego.com%2Fpurchase%2Fbuy-itubego-mac",
  promotedBrandSlug: "itubego",
  headerButtonCTA: "Download HD - All Porn Sites",
  smartlink: "https://flirttalkonline.life/?u=qf5kaeb&o=wgkpxhg",
};

export default siteConfig;