const siteConfig = {
  gitHubRepo: "https://github.com/mattphelps/medal-downloader",
  baseSiteName: "Medal",
  baseSite: "https://medal.com",
  siteName: "Medal Downloader",
  siteURL: "https://medaldownloader.com",
  siteTitle: "Medal Downloader – Download Medal Videos for Free",
  siteDescription: "Want a FAST and FREE way to Download videos from Medal? Download MP4 Videos in HD with one click!",
  faviconPath: "/images/favicons/medal.ico",
  emailFormLink: "https://formspree.io/f/mjvqaqaz",
  adminEmail: "matt@leandme.com",
  downloaderList: "sfw",
  colorTheme: "light",
  buttonColor: "#ffb84c",
  apifyKey: "apify_api_3ladjpBkeHJSHYp2yPv9U594YEbQlD2iJYJ28",
  GATag: "G-E0NGVPCQHJ",
  functional: "yes",
  promotedBrand: "YTSaver",
  promotedBrandURL: "https://www.linkconnector.com/ta.php?lc=165043000012007573&url=https%3A%2F%2Fytsaver.net%2Fbuy%2Fytsaver-for-mac%2F",
  promotedBrandSlug: "ytsaver",
  headerButtonCTA: "Download HD - All Sites",
  smartlink: "https://new-bestfortunes.life/?u=qf5kaeb&o=wgepxhg",
};

export default siteConfig;